/**
 * A broad catalog of software-engineering skills across ALL domains — not just
 * languages and frameworks, but tools, cloud, data/ML, AI dev tools, PM/collab
 * tools, methodologies, and soft skills. Used by `inventory:suggest` to propose
 * a comprehensive candidate list the user prunes to what they've actually done.
 *
 * This is a suggestion source, not a claim — the user decides what stays.
 * Bare single-letter languages ("c", "r") are intentionally omitted — they're
 * low-signal and fragile for word-boundary keyword matching; add them by hand
 * if needed (e.g. "c language").
 */
import type { InventorySkill } from './inventory';

const TECHNICAL: string[] = [
  // Languages
  'python',
  'java',
  'javascript',
  'typescript',
  'c++',
  'c#',
  'go',
  'rust',
  'ruby',
  'kotlin',
  'swift',
  'scala',
  'php',
  'sql',
  'bash',
  'html',
  'css',
  // Frontend
  'react',
  'next.js',
  'vue',
  'angular',
  'svelte',
  'redux',
  'tailwind css',
  'sass',
  'webpack',
  'vite',
  'react native',
  'flutter',
  'accessibility',
  // Backend
  'node.js',
  'express',
  'nestjs',
  'django',
  'flask',
  'fastapi',
  'spring boot',
  'ruby on rails',
  '.net',
  'laravel',
  'graphql',
  'rest apis',
  'grpc',
  'microservices',
  'websockets',
  'oauth',
  // Databases
  'postgresql',
  'mysql',
  'mongodb',
  'redis',
  'sqlite',
  'dynamodb',
  'cassandra',
  'elasticsearch',
  'snowflake',
  'bigquery',
  'prisma',
  'sqlalchemy',
  // Cloud
  'aws',
  'azure',
  'gcp',
  'ec2',
  's3',
  'lambda',
  'cloudformation',
  'vercel',
  'netlify',
  'heroku',
  // DevOps / infra
  'docker',
  'kubernetes',
  'terraform',
  'ansible',
  'jenkins',
  'github actions',
  'gitlab ci',
  'circleci',
  'prometheus',
  'grafana',
  'datadog',
  'nginx',
  'linux',
  // Data / ML
  'pandas',
  'numpy',
  'apache spark',
  'hadoop',
  'kafka',
  'airflow',
  'dbt',
  'tensorflow',
  'pytorch',
  'scikit-learn',
  'jupyter',
  'etl',
  'data pipelines',
  // AI / LLM dev tools
  'openai api',
  'langchain',
  'llamaindex',
  'hugging face',
  'rag',
  'vector databases',
  'pinecone',
  'prompt engineering',
  'github copilot',
  'cursor',
  'chatgpt',
  'claude',
  'llm fine-tuning',
  'embeddings',
  // Testing
  'jest',
  'vitest',
  'pytest',
  'junit',
  'cypress',
  'playwright',
  'selenium',
  'mocha',
  'testing library',
  'tdd',
  // Version control & PM / collaboration tools
  'git',
  'github',
  'gitlab',
  'bitbucket',
  'jira',
  'trello',
  'confluence',
  'linear',
  'asana',
  'notion',
  'slack',
  'figma',
  'postman',
  // Methodologies / practices
  'agile',
  'scrum',
  'kanban',
  'ci/cd',
  'code review',
  'system design',
  'object-oriented programming',
  'functional programming',
  'design patterns',
  'data structures',
  'algorithms',
  'event-driven architecture',
  'caching',
  'observability',
  'security',
  // Mobile
  'ios',
  'android',
  'swiftui',
  'jetpack compose',
];

const SOFT: string[] = [
  'communication',
  'collaboration',
  'cross-functional collaboration',
  'leadership',
  'mentorship',
  'ownership',
  'problem solving',
  'adaptability',
  'time management',
  'stakeholder management',
  'teamwork',
  'attention to detail',
  'initiative',
  'analytical thinking',
  'critical thinking',
  'creativity',
  'customer focus',
  'documentation',
  'presentation',
  'conflict resolution',
];

/** The full catalog, kind-tagged, normalized (lowercased). */
export const SKILL_CATALOG: InventorySkill[] = [
  ...TECHNICAL.map((skill) => ({ skill, kind: 'technical' as const })),
  ...SOFT.map((skill) => ({ skill, kind: 'soft' as const })),
];
